git pull
git push
Set-Location ..
Set-Location Solar_Panel_Protection_System
git pull
git push
Set-Location ..
Set-Location Connect_Four_AI
git pull
git push
Set-Location ..
Set-Location TicTacToe_AI
git pull
git push 
Set-Location ..
Set-Location powershell_scripts